build:
	gcc -g Test.c LinkedList.c ListGraph.c Queue.c p1.c -o p1
	gcc -g Test.c LinkedList.c ListGraph.c Queue.c p2.c -o p2
	gcc -g Test.c LinkedList.c ListGraph.c Queue.c p3.c -o p3
	gcc -g Test.c LinkedList.c ListGraph.c Queue.c p4.c -o p4
	gcc -g Test.c LinkedList.c ListGraph.c Queue.c p5.c -o p5
clean:
	rm p1
	rm p2
	rm p3
	rm p4
	rm p5

